sudo: required

services:
  - docker

install:
  - sudo apt -y update
  - sudo apt -y install curl
  - docker pull mauikit/ubuntu-18.04-amd64

script:
  - docker run --rm -v $(pwd)/:/build/ -w /build/ mauikit/ubuntu-18.04-amd64 /bin/bash travis-build.sh
  - curl --upload-file ./calamares/build/*.deb https://transfersh.com/

branches:
  only:
    - master
    - development
